language: python
python:
  - "3.6"
cache: pip
before_install:
  - mv configuration.template.yaml configuration.yaml
install:
  - pip install -r requirements.test.txt
script:
  - python -m unittest tests/TestStaticListRecords.py